INSERT OR IGNORE INTO quantity (id, name, symbol, science, branch, topic, difficulty, default_unit, dim_M, dim_L, dim_T, dim_I, dim_Θ, dim_N, dim_J) VALUES
  ('angle',
   '{"en-us": "Plane angle"}',
   '\theta',
   '{"en-us": "Physics"}',
   '{"en-us": "Geometry"}',
   '{"en-us": "Trigonometry"}',
   1,
   '[{"unit": "radian", "exponent": 1}]',
   0,0,0,0,0,0,0),
  ('solid_angle',
   '{"en-us": "Solid angle"}',
   '\Omega',
   '{"en-us": "Physics"}',
   '{"en-us": "Geometry"}',
   '{"en-us": "Trigonometry"}',
   2,
   '[{"unit": "steradian", "exponent": 1}]',
   0,0,0,0,0,0,0),
  ('frequency',
   '{"en-us": "Frequency"}',
   'f',
   '{"en-us": "Physics"}',
   '{"en-us": "Classical mechanics"}',
   '{"en-us": "Waves"}',
   2,
   '[{"unit": "hertz", "exponent": 1}]',
   0,0,-1,0,0,0,0),
  ('power',
   '{"en-us": "Power"}',
   'P',
   '{"en-us": "Physics"}',
   '{"en-us": "Classical mechanics"}',
   '{"en-us": "Energy"}',
   2,
   '[{"unit": "watt", "exponent": 1}]',
   1,2,-3,0,0,0,0),
  ('charge',
   '{"en-us": "Electric charge"}',
   'Q',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Electrostatics"}',
   2,
   '[{"unit": "coulomb", "exponent": 1}]',
   0,0,1,1,0,0,0),
  ('electric_potential',
   '{"en-us": "Electric potential"}',
   'V',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Electrostatics"}',
   3,
   '[{"unit": "volt", "exponent": 1}]',
   1,2,-3,-1,0,0,0),
  ('conductance',
   '{"en-us": "Electrical conductance"}',
   'G',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Circuits"}',
   3,
   '[{"unit": "siemens", "exponent": 1}]',
   -1,-2,3,2,0,0,0),
  ('capacitance',
   '{"en-us": "Capacitance"}',
   'C',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Circuits"}',
   3,
   '[{"unit": "farad", "exponent": 1}]',
   -1,-2,4,2,0,0,0),
  ('inductance',
   '{"en-us": "Inductance"}',
   'L',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Circuits"}',
   3,
   '[{"unit": "henry", "exponent": 1}]',
   1,2,-2,-2,0,0,0),
  ('magnetic_flux_density',
   '{"en-us": "Magnetic flux density"}',
   'B',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Magnetism"}',
   3,
   '[{"unit": "tesla", "exponent": 1}]',
   1,0,-2,-1,0,0,0),
  ('magnetic_flux',
   '{"en-us": "Magnetic flux"}',
   '\Phi',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Magnetism"}',
   3,
   '[{"unit": "weber", "exponent": 1}]',
   1,2,-2,-1,0,0,0),
  ('luminous_flux',
   '{"en-us": "Luminous flux"}',
   '\Phi_v',
   '{"en-us": "Physics"}',
   '{"en-us": "Optics"}',
   '{"en-us": "Photometry"}',
   3,
   '[{"unit": "lumen", "exponent": 1}]',
   0,0,0,0,0,0,1),
  ('illuminance',
   '{"en-us": "Illuminance"}',
   'E_v',
   '{"en-us": "Physics"}',
   '{"en-us": "Optics"}',
   '{"en-us": "Photometry"}',
   3,
   '[{"unit": "lux", "exponent": 1}]',
   0,-2,0,0,0,0,1),
  ('activity',
   '{"en-us": "Activity"}',
   'A',
   '{"en-us": "Physics"}',
   '{"en-us": "Nuclear physics"}',
   '{"en-us": "Radioactivity"}',
   3,
   '[{"unit": "becquerel", "exponent": 1}]',
   0,0,-1,0,0,0,0),
  ('absorbed_dose',
   '{"en-us": "Absorbed dose"}',
   'D',
   '{"en-us": "Physics"}',
   '{"en-us": "Nuclear physics"}',
   '{"en-us": "Radiation"}',
   4,
   '[{"unit": "gray", "exponent": 1}]',
   0,2,-2,0,0,0,0),
  ('dose_equivalent',
   '{"en-us": "Dose equivalent"}',
   'H',
   '{"en-us": "Physics"}',
   '{"en-us": "Nuclear physics"}',
   '{"en-us": "Radiation"}',
   4,
   '[{"unit": "sievert", "exponent": 1}]',
   0,2,-2,0,0,0,0),
  ('catalytic_activity',
   '{"en-us": "Catalytic activity"}',
   'k',
   '{"en-us": "Chemistry"}',
   '{"en-us": "Physical chemistry"}',
   '{"en-us": "Kinetics"}',
   3,
   '[{"unit": "katal", "exponent": 1}]',
   0,0,-1,0,0,1,0),
  ('area',
   '{"en-us": "Area"}',
   'A',
   '{"en-us": "Mathematics"}',
   '{"en-us": "Geometry"}',
   '{"en-us": "Area"}',
   1,
   '[{"unit": "square_metre", "exponent": 1}]',
   0,2,0,0,0,0,0),
  ('density',
   '{"en-us": "Density"}',
   '\rho',
   '{"en-us": "Physics"}',
   '{"en-us": "Thermodynamics"}',
   '{"en-us": "Continuum mechanics"}',
   2,
   '[{"unit": "kilogram", "exponent": 1}, {"unit": "cubic_metre", "exponent": -1}]',
   1,-3,0,0,0,0,0),
  ('surface_density',
   '{"en-us": "Surface density"}',
   '\rho_A',
   '{"en-us": "Physics"}',
   '{"en-us": "Thermodynamics"}',
   '{"en-us": "Continuum mechanics"}',
   3,
   '[{"unit": "kilogram", "exponent": 1}, {"unit": "square_metre", "exponent": -1}]',
   1,-2,0,0,0,0,0),
  ('specific_volume',
   '{"en-us": "Specific volume"}',
   'v',
   '{"en-us": "Physics"}',
   '{"en-us": "Thermodynamics"}',
   '{"en-us": "Continuum mechanics"}',
   3,
   '[{"unit": "cubic_metre", "exponent": 1}, {"unit": "kilogram", "exponent": -1}]',
   -1,3,0,0,0,0,0),
  ('current_density',
   '{"en-us": "Current density"}',
   'j',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Circuits"}',
   3,
   '[{"unit": "ampere", "exponent": 1}, {"unit": "square_metre", "exponent": -1}]',
   0,-2,0,1,0,0,0),
  ('magnetic_field_strength',
   '{"en-us": "Magnetic field strength"}',
   'H',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Magnetism"}',
   3,
   '[{"unit": "ampere", "exponent": 1}, {"unit": "metre", "exponent": -1}]',
   0,-1,0,1,0,0,0),
  ('concentration',
   '{"en-us": "Concentration"}',
   'c',
   '{"en-us": "Chemistry"}',
   '{"en-us": "Physical chemistry"}',
   '{"en-us": "Solutions"}',
   2,
   '[{"unit": "mole", "exponent": 1}, {"unit": "cubic_metre", "exponent": -1}]',
   0,-3,0,0,0,1,0),
  ('mass_concentration',
   '{"en-us": "Mass concentration"}',
   '\gamma',
   '{"en-us": "Chemistry"}',
   '{"en-us": "Physical chemistry"}',
   '{"en-us": "Solutions"}',
   3,
   '[{"unit": "kilogram", "exponent": 1}, {"unit": "cubic_metre", "exponent": -1}]',
   1,-3,0,0,0,0,0),
  ('luminance',
   '{"en-us": "Luminance"}',
   'L_v',
   '{"en-us": "Physics"}',
   '{"en-us": "Optics"}',
   '{"en-us": "Photometry"}',
   3,
   '[{"unit": "candela", "exponent": 1}, {"unit": "square_metre", "exponent": -1}]',
   0,-2,0,0,0,0,1),
  ('wavenumber',
   '{"en-us": "Wavenumber"}',
   '\tilde{\nu}',
   '{"en-us": "Physics"}',
   '{"en-us": "Optics"}',
   '{"en-us": "Waves"}',
   3,
   '[{"unit": "reciprocal_metre", "exponent": 1}]',
   0,-1,0,0,0,0,0),
  ('dynamic_viscosity',
   '{"en-us": "Dynamic viscosity"}',
   '\eta',
   '{"en-us": "Physics"}',
   '{"en-us": "Fluid mechanics"}',
   '{"en-us": "Viscosity"}',
   3,
   '[{"unit": "pascal_second", "exponent": 1}]',
   1,-1,-1,0,0,0,0),
  ('torque',
   '{"en-us": "Torque"}',
   '\tau',
   '{"en-us": "Physics"}',
   '{"en-us": "Classical mechanics"}',
   '{"en-us": "Rotation"}',
   3,
   '[{"unit": "newton_metre", "exponent": 1}]',
   1,2,-2,0,0,0,0),
  ('surface_tension',
   '{"en-us": "Surface tension"}',
   '\gamma',
   '{"en-us": "Physics"}',
   '{"en-us": "Fluid mechanics"}',
   '{"en-us": "Surface phenomena"}',
   3,
   '[{"unit": "newton_per_metre", "exponent": 1}]',
   1,0,-2,0,0,0,0),
  ('angular_velocity',
   '{"en-us": "Angular velocity"}',
   '\omega',
   '{"en-us": "Physics"}',
   '{"en-us": "Classical mechanics"}',
   '{"en-us": "Rotation"}',
   3,
   '[{"unit": "radian_per_second", "exponent": 1}]',
   0,0,-1,0,0,0,0),
  ('angular_acceleration',
   '{"en-us": "Angular acceleration"}',
   '\alpha',
   '{"en-us": "Physics"}',
   '{"en-us": "Classical mechanics"}',
   '{"en-us": "Rotation"}',
   3,
   '[{"unit": "radian_per_second_sq", "exponent": 1}]',
   0,0,-2,0,0,0,0),
  ('irradiance',
   '{"en-us": "Irradiance"}',
   'E',
   '{"en-us": "Physics"}',
   '{"en-us": "Optics"}',
   '{"en-us": "Radiometry"}',
   3,
   '[{"unit": "watt_per_square_metre", "exponent": 1}]',
   1,0,-3,0,0,0,0),
  ('entropy',
   '{"en-us": "Entropy"}',
   'S',
   '{"en-us": "Physics"}',
   '{"en-us": "Thermodynamics"}',
   '{"en-us": "Second law"}',
   3,
   '[{"unit": "joule_per_kelvin", "exponent": 1}]',
   1,2,-2,0,-1,0,0),
  ('specific_heat_capacity',
   '{"en-us": "Specific heat capacity"}',
   'c',
   '{"en-us": "Physics"}',
   '{"en-us": "Thermodynamics"}',
   '{"en-us": "Heat transfer"}',
   3,
   '[{"unit": "joule_per_kilogram_kelvin", "exponent": 1}]',
   0,2,-2,0,-1,0,0),
  ('specific_energy',
   '{"en-us": "Specific energy"}',
   'e',
   '{"en-us": "Physics"}',
   '{"en-us": "Thermodynamics"}',
   '{"en-us": "Energy"}',
   3,
   '[{"unit": "joule_per_kilogram", "exponent": 1}]',
   0,2,-2,0,0,0,0),
  ('thermal_conductivity',
   '{"en-us": "Thermal conductivity"}',
   'k',
   '{"en-us": "Physics"}',
   '{"en-us": "Thermodynamics"}',
   '{"en-us": "Heat transfer"}',
   3,
   '[{"unit": "watt_per_metre_kelvin", "exponent": 1}]',
   1,1,-3,0,-1,0,0),
  ('energy_density',
   '{"en-us": "Energy density"}',
   'u',
   '{"en-us": "Physics"}',
   '{"en-us": "Thermodynamics"}',
   '{"en-us": "Energy"}',
   3,
   '[{"unit": "joule_per_cubic_metre", "exponent": 1}]',
   1,-1,-2,0,0,0,0),
  ('electric_field_strength',
   '{"en-us": "Electric field strength"}',
   'E',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Electrostatics"}',
   3,
   '[{"unit": "volt_per_metre", "exponent": 1}]',
   1,1,-3,-1,0,0,0),
  ('charge_density',
   '{"en-us": "Electric charge density"}',
   '\rho',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Electrostatics"}',
   3,
   '[{"unit": "coulomb_per_cubic_metre", "exponent": 1}]',
   0,-3,1,1,0,0,0),
  ('surface_charge_density',
   '{"en-us": "Surface charge density"}',
   '\sigma',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Electrostatics"}',
   3,
   '[{"unit": "coulomb_per_square_metre", "exponent": 1}]',
   0,-2,1,1,0,0,0),
  ('permittivity',
   '{"en-us": "Permittivity"}',
   '\varepsilon',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Electrostatics"}',
   4,
   '[{"unit": "farad_per_metre", "exponent": 1}]',
   -1,-3,4,2,0,0,0),
  ('permeability',
   '{"en-us": "Permeability"}',
   '\mu',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Magnetism"}',
   4,
   '[{"unit": "henry_per_metre", "exponent": 1}]',
   1,1,-2,-2,0,0,0),
  ('molar_energy',
   '{"en-us": "Molar energy"}',
   'E_m',
   '{"en-us": "Chemistry"}',
   '{"en-us": "Physical chemistry"}',
   '{"en-us": "Thermochemistry"}',
   3,
   '[{"unit": "joule_per_mole", "exponent": 1}]',
   1,2,-2,0,0,-1,0),
  ('molar_entropy',
   '{"en-us": "Molar entropy"}',
   'S_m',
   '{"en-us": "Chemistry"}',
   '{"en-us": "Physical chemistry"}',
   '{"en-us": "Thermochemistry"}',
   3,
   '[{"unit": "joule_per_mole_kelvin", "exponent": 1}]',
   1,2,-2,0,-1,-1,0),
  ('exposure',
   '{"en-us": "Exposure"}',
   'X',
   '{"en-us": "Physics"}',
   '{"en-us": "Nuclear physics"}',
   '{"en-us": "Radiation"}',
   4,
   '[{"unit": "coulomb_per_kilogram", "exponent": 1}]',
   -1,0,1,1,0,0,0),
  ('absorbed_dose_rate',
   '{"en-us": "Absorbed dose rate"}',
   '\dot{D}',
   '{"en-us": "Physics"}',
   '{"en-us": "Nuclear physics"}',
   '{"en-us": "Radiation"}',
   4,
   '[{"unit": "gray_per_second", "exponent": 1}]',
   0,2,-3,0,0,0,0),
  ('radiant_intensity',
   '{"en-us": "Radiant intensity"}',
   'I_e',
   '{"en-us": "Physics"}',
   '{"en-us": "Optics"}',
   '{"en-us": "Radiometry"}',
   4,
   '[{"unit": "watt_per_steradian", "exponent": 1}]',
   1,2,-3,0,0,0,0),
  ('radiance',
   '{"en-us": "Radiance"}',
   'L_e',
   '{"en-us": "Physics"}',
   '{"en-us": "Optics"}',
   '{"en-us": "Radiometry"}',
   4,
   '[{"unit": "watt_per_square_metre_steradian", "exponent": 1}]',
   1,0,-3,0,0,0,0),
  ('catalytic_activity_concentration',
   '{"en-us": "Catalytic activity concentration"}',
   'k_v',
   '{"en-us": "Chemistry"}',
   '{"en-us": "Physical chemistry"}',
   '{"en-us": "Kinetics"}',
   4,
   '[{"unit": "katal_per_cubic_metre", "exponent": 1}]',
   0,-3,-1,0,0,1,0),
  ('electric_current',
   '{"en-us": "Electric current"}',
   'I',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Circuits"}',
   2,
   '[{"unit": "ampere", "exponent": 1}]',
   0,0,0,1,0,0,0),
  ('luminous_intensity',
   '{"en-us": "Luminous intensity"}',
   'I_v',
   '{"en-us": "Physics"}',
   '{"en-us": "Optics"}',
   '{"en-us": "Photometry"}',
   3,
   '[{"unit": "candela", "exponent": 1}]',
   0,0,0,0,0,0,1)
;

-- ============================================================
-- New units
-- ============================================================
INSERT OR IGNORE INTO unit (id, name, symbol, quantity_id, default_unit, unit_system, factor, latex_factor, offset) VALUES
('ampere', '{"en-us": "Ampere"}', 'A', 'electric_current', 1, 'SI', 1, NULL, 0),
('mole', '{"en-us": "Mole"}', 'mol', 'amount', 1, 'SI', 1, NULL, 0),
('candela', '{"en-us": "Candela"}', 'cd', 'luminous_intensity', 1, 'SI', 1, NULL, 0),
('radian', '{"en-us": "Radian"}', 'rad', 'angle', 1, 'SI', 1, NULL, 0),
('steradian', '{"en-us": "Steradian"}', 'sr', 'solid_angle', 1, 'SI', 1, NULL, 0),
('hertz', '{"en-us": "Hertz"}', 'Hz', 'frequency', 1, 'SI', 1, NULL, 0),
('pascal', '{"en-us": "Pascal"}', 'Pa', 'pressure', 1, 'SI', 1, NULL, 0),
('joule', '{"en-us": "Joule"}', 'J', 'energy', 1, 'SI', 1, NULL, 0),
('watt', '{"en-us": "Watt"}', 'W', 'power', 1, 'SI', 1, NULL, 0),
('coulomb', '{"en-us": "Coulomb"}', 'C', 'charge', 1, 'SI', 1, NULL, 0),
('volt', '{"en-us": "Volt"}', 'V', 'electric_potential', 1, 'SI', 1, NULL, 0),
('siemens', '{"en-us": "Siemens"}', 'S', 'conductance', 1, 'SI', 1, NULL, 0),
('farad', '{"en-us": "Farad"}', 'F', 'capacitance', 1, 'SI', 1, NULL, 0),
('henry', '{"en-us": "Henry"}', 'H', 'inductance', 1, 'SI', 1, NULL, 0),
('tesla', '{"en-us": "Tesla"}', 'T', 'magnetic_flux_density', 1, 'SI', 1, NULL, 0),
('weber', '{"en-us": "Weber"}', 'Wb', 'magnetic_flux', 1, 'SI', 1, NULL, 0),
('lumen', '{"en-us": "Lumen"}', 'lm', 'luminous_flux', 1, 'SI', 1, NULL, 0),
('lux', '{"en-us": "Lux"}', 'lx', 'illuminance', 1, 'SI', 1, NULL, 0),
('becquerel', '{"en-us": "Becquerel"}', 'Bq', 'activity', 1, 'SI', 1, NULL, 0),
('gray', '{"en-us": "Gray"}', 'Gy', 'absorbed_dose', 1, 'SI', 1, NULL, 0),
('sievert', '{"en-us": "Sievert"}', 'Sv', 'dose_equivalent', 1, 'SI', 1, NULL, 0),
('katal', '{"en-us": "Katal"}', 'kat', 'catalytic_activity', 1, 'SI', 1, NULL, 0),
('minute', '{"en-us": "Minute"}', 'min', 'period', 0, NULL, 60, NULL, 0),
('hour', '{"en-us": "Hour"}', 'h', 'period', 0, NULL, 3600, NULL, 0),
('day', '{"en-us": "Day"}', 'd', 'period', 0, NULL, 86400, NULL, 0),
('astronomical_unit', '{"en-us": "Astronomical unit"}', 'au', 'length', 0, NULL, 149597870700, NULL, 0),
('degree', '{"en-us": "Degree"}', '{}^{\circ}', 'angle', 0, NULL, 0.017453292519943295, NULL, 0),
('hectare', '{"en-us": "Hectare"}', 'ha', 'area', 0, NULL, 10000, NULL, 0),
('litre', '{"en-us": "Litre"}', 'L', 'volume', 0, NULL, 0.001, NULL, 0),
('tonne', '{"en-us": "Tonne"}', 't', 'mass', 0, NULL, 1000, NULL, 0),
('dalton', '{"en-us": "Dalton"}', 'Da', 'mass', 0, NULL, 1.66053906892e-27, NULL, 0),
('electronvolt', '{"en-us": "Electronvolt"}', 'eV', 'energy', 0, NULL, 1.602176634e-19, NULL, 0),
('neper', '{"en-us": "Neper"}', 'Np', 'angle', 0, NULL, 1, NULL, 0),
('bel', '{"en-us": "Bel"}', 'B', 'angle', 0, NULL, 1, NULL, 0),
('decibel', '{"en-us": "Decibel"}', 'dB', 'angle', 0, NULL, 0.1, NULL, 0),
('arcminute', '{"en-us": "Arcminute"}', '{}^{\prime}', 'angle', 0, NULL, 0.0002908882086657216, NULL, 0),
('arcsecond', '{"en-us": "Arcsecond"}', '{}^{\prime\prime}', 'angle', 0, NULL, 4.84813681109536e-06, NULL, 0)
;

-- ============================================================
-- Update existing quantities' default_unit
-- ============================================================
UPDATE quantity SET default_unit = '[{"unit": "joule", "exponent": 1}]' WHERE id = 'energy' AND default_unit IS NULL;
UPDATE quantity SET default_unit = '[{"unit": "pascal", "exponent": 1}]' WHERE id = 'pressure' AND default_unit IS NULL;
UPDATE quantity SET default_unit = '[{"unit": "metre", "exponent": 3}]' WHERE id = 'volume' AND default_unit IS NULL;
UPDATE quantity SET default_unit = '[{"unit": "metre", "exponent": 1}, {"unit": "second", "exponent": -1}]' WHERE id = 'velocity' AND default_unit IS NULL;
UPDATE quantity SET default_unit = '[{"unit": "metre", "exponent": 1}, {"unit": "second", "exponent": -2}]' WHERE id = 'acceleration' AND default_unit IS NULL;
UPDATE quantity SET default_unit = '[{"unit": "joule", "exponent": 1}]' WHERE id = 'work' AND default_unit IS NULL;
UPDATE quantity SET default_unit = '[{"unit": "joule", "exponent": 1}]' WHERE id = 'heat' AND default_unit IS NULL;
UPDATE quantity SET default_unit = '[{"unit": "joule", "exponent": 1}]' WHERE id = 'internal_energy' AND default_unit IS NULL;
UPDATE quantity SET default_unit = '[{"unit": "joule", "exponent": 1}, {"unit": "mole", "exponent": -1}, {"unit": "kelvin", "exponent": -1}]' WHERE id = 'gas_constant' AND default_unit IS NULL;
UPDATE quantity SET default_unit = '[{"unit": "mole", "exponent": 1}]' WHERE id = 'amount' AND default_unit IS NULL;
UPDATE quantity SET default_unit = '[{"unit": "kilogram", "exponent": 1}, {"unit": "metre", "exponent": 1}, {"unit": "second", "exponent": -1}]' WHERE id = 'momentum' AND default_unit IS NULL;
UPDATE quantity SET default_unit = '[{"unit": "ampere", "exponent": 1}]' WHERE id = 'electric_current' AND default_unit IS NULL;
UPDATE quantity SET default_unit = '[{"unit": "candela", "exponent": 1}]' WHERE id = 'luminous_intensity' AND default_unit IS NULL;